apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-search
  namespace: paas3
  labels:
    app: vector-search
spec:
  selector:
    matchLabels:
      octopusexport: OctopusExport
  replicas: 1
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: vector-search
        octopusexport: OctopusExport
    spec:
      containers:
        - name: app
          image: '660124699787.dkr.ecr.ap-south-1.amazonaws.com/vector-search:0.0.1'
          ports:
            - name: http
              containerPort: 5001
              protocol: TCP
          resources:
            limits:
              memory: 4Gi
              cpu: "2"
---
apiVersion: v1
kind: Service
metadata:
  name: vector-search
  namespace: paas3
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: http
  selector:
    app: vector-search
  type: ClusterIP
