name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the server Docker image
      run: |
        cd server
        docker build . --file Dockerfile --tag 660124699787.dkr.ecr.ap-south-1.amazonaws.com/vector-search:$(date +%s)
